### ISSUE TITLE
Does not work with CC:Tweaked 1.113.0

### ISSUE THREAD

**Issue by hatkidchan** [SwitchCraftCC/Plethora-Fabric#106]
Plethora: 1.11.7
CC:Tweaked: 1.113.0
Fabric: 0.16.2
Fabric API: 0.92.2+1.20.1

Player gets kicked on login with a following error message:
```
net.minecraft.util.crash.CrashException: Ticking player
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:574) ~[server-intermediary.jar:?]
	at net.minecraft.server.network.ServerPlayNetworkHandler.tick(ServerPlayNetworkHandler.java:269) ~[server-intermediary.jar:?]
	at net.minecraft.network.ClientConnection.tick(ClientConnection.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.server.dedicated.MinecraftDedicatedServer.tickWorlds(MinecraftDedicatedServer.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:671) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'void dan200.computercraft.shared.computer.core.ServerComputer.<init>(net.minecraft.server.world.ServerWorld, net.minecraft.util.math.BlockPos, int, java.lang.String, dan200.computercraft.shared.computer.core.ComputerFamily, int, int)'
	at io.sc3.plethora.gameplay.neural.NeuralComputer.<init>(NeuralComputer.kt:29) ~[Plethora-Fabric-1.11.7.jar:?]
	at io.sc3.plethora.gameplay.neural.NeuralComputerHandler.getServer(NeuralComputerHandler.java:57) ~[Plethora-Fabric-1.11.7.jar:?]
	at io.sc3.plethora.gameplay.neural.NeuralInterfaceItem$Companion.onUpdate(NeuralInterfaceItem.kt:81) ~[Plethora-Fabric-1.11.7.jar:?]
	at io.sc3.plethora.gameplay.neural.NeuralInterfaceItem$Companion.access$onUpdate(NeuralInterfaceItem.kt:74) ~[Plethora-Fabric-1.11.7.jar:?]
	at io.sc3.plethora.gameplay.neural.NeuralInterfaceItem.tick(NeuralInterfaceItem.kt:71) ~[Plethora-Fabric-1.11.7.jar:?]
	at net.minecraft.entity.LivingEntity.mdec07ea$trinkets$lambda$tick$2$14(LivingEntity.java:33814) ~[server-intermediary.jar:?]
	at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.2.jar:?]
	at net.minecraft.entity.LivingEntity.mdec07ea$trinkets$lambda$tick$3$13(LivingEntity.java:33759) ~[server-intermediary.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.entity.LivingEntity.handler$gba00d$trinkets$tick(LivingEntity.java:33756) ~[server-intermediary.jar:?]
	at net.minecraft.entity.LivingEntity.tick(LivingEntity.java:2499) ~[server-intermediary.jar:?]
	at net.minecraft.entity.player.PlayerEntity.tick(PlayerEntity.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.network.ServerPlayerEntity.playerTick(ServerPlayerEntity.java:510) ~[server-intermediary.jar:?]
	... 9 more
```

**Comment by lexi-the-cute** [comment]
the latest version of cc: tweaked that doesn't cause a crash when wearing a neural module is 1.111.0
